def get_help() -> str:
    """Return RogueBot's available commands."""

    return (
        "Here's what I can do. "
        "Morning briefing: 'good morning'. "
        "Time and date: 'what time is it', 'what day is it'. "
        "Weather: 'what's the weather', 'weather in Tokyo'. "
        "System: 'system status', 'battery', 'temperature'. "
        "Timer: 'set a timer for 5 minutes', 'list timers', 'cancel timers'. "
        "Reminder: 'remind me at 3pm to call the dentist', 'list reminders'. "
        "Lists: 'add milk to my shopping list', 'read my shopping list'. "
        "Memory: 'remember that something is something', 'what is something'. "
        "Clipboard: 'read my clipboard', 'summarise this', 'explain this', 'fix the grammar', 'translate this to Spanish'. "
        "Screen: 'describe my screen', 'what's on my screen'. "
        "Dictation: 'start dictating'. "
        "Apps: 'open Spotify', 'open Chrome', 'open GitHub'. "
        "Media: 'volume up', 'volume down', 'mute', 'next track', 'pause'. "
        "Dictionary: 'define serendipity', 'how do you spell necessary'. "
        "News: 'what's in the news'. "
        "Search: 'search for SpaceX', 'look up the Eiffel Tower'. "
        "Math: 'what is 15 percent of 340', 'convert 72 fahrenheit to celsius'. "
        "History: 'what did I ask you before', 'show my last 5 commands'. "
        "Other: 'repeat that', 'reload skills'. "
        "Say 'goodbye' or 'shutdown' to turn me off."
    )
